#!/bin/bash -e

ip link add wg0 type wireguard
wg set wg0 listen-port 51280 private-key /dev/stdin \
  <<< "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

wg set wg0 peer "MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA=" \
  allowed-ips 2a01:4f8:c17:ac0f::a

ip link set wg0 up
ip address add 2a01:4f8:c17:ac0f::1/64 dev wg0
